### ISSUE TITLE
Failing to display

### ISSUE THREAD

**Issue by JustinTQ** [cornerstonejs/cornerstoneWADOImageLoader#141]
Hi sir,
### Why is this picture open is blank?
![20171110100743](https://user-images.githubusercontent.com/20768697/32640068-c43ff5a0-c601-11e7-9c60-6977851d18cd.png)
Anyone can tell me how to solve it.
Thank you very much!
[1.3.12.2.1107.5.1.4.54308.zip](https://github.com/chafey/cornerstoneWADOImageLoader/files/1459896/1.3.12.2.1107.5.1.4.54308.zip)

**Comment by swederik** [comment]
I can't seem to get a DICOM file out of your ZIP. I just get something with '.cpgz'.

I would guess that it has something to do with the Min / Max Stored Pixel Values both marked as 0.
