### ISSUE TITLE
Some dicom file can't show on wado image loader

### ISSUE THREAD

**Issue by flyhuang** [cornerstonejs/cornerstoneWADOImageLoader#143]
Hi sir,

<img width="1094" alt="screen shot 2017-11-14 at 2 47 53 pm" src="https://user-images.githubusercontent.com/1689430/32766660-e7492aa2-c94a-11e7-928e-6c66888ed894.png">

This is my dicom file
[1.2.840.1.99.1.47.1.1510543940.1104.zip](https://github.com/chafey/cornerstoneWADOImageLoader/files/1469808/1.2.840.1.99.1.47.1.1510543940.1104.zip)

Could u give me some suggestion for this case?

Thanks very much,
Wade Huang

**Comment by flyhuang** [comment]
Hi @swederik,

Cloud u give me some suggestion about this?

it's dicom parser lib issue or cornerstone canvas show issue?

Thanks,
Wade Huang

**Comment by swederik** [comment]
Hi Wade,

Sorry I haven't had time yet to look into this. I just took a look and it's a bit bizarre. Let me dig a little deeper.

**Comment by flyhuang** [comment]
Thanks very much @swederik

**Comment by swederik** [comment]
Hi Wade,

It appears that you have a secondary capture image which has retained the original image's window width / center and rescale slope / intercept values. If you look at the file you have slope = 1, intercept = -1024, and window width 2000, center 500, but this is an RGB image. The modality and VOI LUTs were being created and applied to the stored pixels for this image, and all the values were ending up as 0, so your image was black.

I'm not certain what to do about this right now, but I am wondering if we should even be applying modality LUTs for color photometric interpretations.

**Comment by swederik** [comment]
If you try your file here it will work:

https://rawgit.com/chafey/cornerstoneWADOImageLoader/color/examples/dicomfile/index.html

I will try to confirm this approach is okay before I merge these changes into WADO Image Loader / Cornerstone Core.

**Comment by flyhuang** [comment]
Hi @swederik 

Thanks for your valuable time, it works!!

**Comment by swederik** [comment]
Your file works now on the live site, so I'll close this. Thanks for the report!
