### ISSUE TITLE
Can cornerstone WADO image loader clear memory after finish decode image

### ISSUE THREAD

**Issue by doananhbao94** [cornerstonejs/cornerstoneWADOImageLoader#148]
Hi sir, I have a question wanna to ask you.

Can the cornerstone WADO image loader clear memory after finish all task decode image?

I use the image return and use the method decache but i seen it not work. 

Please help me. Thank you

**Comment by dannyrb** [comment]
@doananhbao94, are you still experiencing this issue? Are you able to provide a minimal reproduction? If you are, please feel free to comment here and I'll do my best to respond.

As this question's a bit older, I'm going to close it for now. If our discussion resumes, I'll open the issue.
