### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstoneWADOImageLoader#153]
(on windows)
```

npm test

...

15 12 2017 09:02:52.737:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket oaWAcJvj5zrqemC-AAAA with id 17628610
PhantomJS 2.1.1 (Windows 8 0.0.0) decodeImageFrame should properly decode LittleEndianImplicitTransferSyntax FAILED
        TypeError: undefined is not a constructor (evaluating 'cornerstone.triggerEvent(cornerstone.events, 'cornerstoneimageloadstart', event
Data)') (test/decoders_test.js:3459)

```

I think the issue is that the test relies on window.cornerstone which is undefined

Any help ?

Thanks!

**Comment by swederik** [comment]
I can't seem to reproduce this. Is it still occurring for you? I am using Windows 10.

**Comment by kofifus** [comment]
ok I got this to work and now have the ES6 direct loading working properly in https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/171
