### ISSUE TITLE
README dead example 

### ISSUE THREAD

**Issue by Spown** [cornerstonejs/cornerstoneWADOImageLoader#155]
> You can also see it in action with the [cornerstoneDemo application](https://github.com/cornerstonejs/cornerstoneDemo).

it's dead, Jim.

**Comment by dannyrb** [comment]
Thanks, @Spown. You can find that link here: https://github.com/chafey/cornerstoneDemo

I'll close this issue when we get around to updating/fixing the link.

**Comment by dannyrb** [comment]
Fixed here: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/commit/f7476cab7f88e035f7978f8df2b4b95968921092
