### ISSUE TITLE
Memory Leak on loadImage()

### ISSUE THREAD

**Issue by agustingrigoriu** [cornerstonejs/cornerstoneWADOImageLoader#156]
Hi, I'm having trouble while loading some images, I have the following layout, which I can change by selecting the "modes" you can see in the toolbar:
![screenshot-2017-12-27 studies](https://user-images.githubusercontent.com/19197433/34387121-191226f6-eb0b-11e7-8042-11d8bc135e84.png)
But every time I change the mode, the memory usage increases, until I reach a point everything crashes.
Here is a screenshot of the memory heap after I compare two snapshots, one taken at the beginning and one after changing modes and returning to the original:
![imagen](https://user-images.githubusercontent.com/19197433/34387208-8d5484be-eb0b-11e7-98b3-94d708d202ee.png)

**Comment by dannyrb** [comment]
@agustingrigoriu can you provide some additional information around this report?

- Can you create a reproducible example in [codepen](https://codepen.io/pen/) or [jsfiddle](https://jsfiddle.net/)?
- What cornerstone api calls are being made when you switch modes?
- Do you see anything odd happening in your network tab?

**Comment by leonardorame** [comment]
Hi, this is a working example, please take into account it won't work from the filesystem, this .html file must be run from a webserver.

```<html lang="en-us">

<head>
  <meta charset="utf-8">
  <title>Test</title>
  <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css">
</head>

<body>

  <div style="display: block; width: 100%; height: 100vh !important; overflow: hidden;">
    <div style="width: 100%;">
      <nav class="navbar navbar-default" style="margin-bottom:0px">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">
              Test
            </a>
          </div>
        </div>
      </nav>

      <div class="btn-group" role="group" aria-label="Modalities">
        <button id="btnIm1" type="button" class="btn btn-default">IM1</button>
        <button id="btnIm2" type="button" class="btn btn-default">IM2</button>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div style="width:512px;height:512px;position:relative;display:inline-block;color:white;" oncontextmenu="return false" class='cornerstone-enabled-image'
          unselectable='on' onselectstart='return false;' onmousedown='return false;'>
          <div id="dicom" style="border: 1px solid red; width:512px;height:512px;top:0px;left:0px; position:absolute;">
          </div>
        </div>
      </div>

    </div>
    <script src="js/libs/jquery-2.1.1.min.js"></script>

    <script src="js/cornerstone/cornerstone.min.js"></script>
    <script src="js/cornerstone/cornerstoneMath.js"></script>
    <script src="js/cornerstone/dicomParser.min.js"></script>
    <script src="js/cornerstone/cornerstoneWADOImageLoader.min.js"></script>
    <script src="js/cornerstone/cornerstoneTools.min.js"></script>

    <script>

        cornerstoneWADOImageLoader.external.cornerstone = cornerstone;

        var config = {
          webWorkerPath: "js/cornerstone/cornerstoneWADOImageLoaderWebWorker.min.js",
          taskConfiguration: {
            decodeTask: {
              codecsPath: "/js/cornerstone/cornerstoneWADOImageLoaderCodecs.min.js"
            }
          }
        };

        cornerstoneWADOImageLoader.webWorkerManager.initialize(config);

        var imagesIds = [
          "wadouri:http://45.63.8.72/examples/1.dcm",
          "wadouri:http://45.63.8.72/examples/2.dcm"
        ];

        var init = function () {
          openImage("IM1");
          setupEvents();
        };

        // Obtengo imagen y la coloco en el div correspondiente.
        var openImage = function (image) {
          var element = document.getElementById('dicom');


          var imageId = "";
          if (image == "IM1") {
            imageId = imagesIds[0];
          } else if (image == "IM2") {
            imageId = imagesIds[1];
          }

          cornerstone.enable(element);
          console.log("ANTES DE ENTRAR");
          console.log(imageId);
          cornerstone.loadImage(imageId).then(function (dicomImage) {
            console.log("ENTRE A LOAD IMAGE");
            cornerstone.displayImage(element, dicomImage);
            cornerstoneTools.mouseInput.enable(element);
            cornerstoneTools.mouseWheelInput.enable(element);
            cornerstoneTools.wwwc.activate(element, 1); // Left Click
            cornerstoneTools.pan.activate(element, 2); // Middle Click
            cornerstoneTools.zoom.activate(element, 4); // Right Click
            cornerstoneTools.zoomWheel.activate(element); // Mouse Wheel
            cornerstone.draw(element);
          });
        };

        var setupEvents = function () {
          $("#btnIm1").click(function () {
            openImage("IM1");
          });

          $("#btnIm2").click(function () {
            openImage("IM2");
          });
        };

      init();
    </script>
</body>

</html>
```

Usage is very simple, when the page opens it loads the 1nst image, then you must click on im2 to load the 2nd, then click again in IM1 and so on. If you go to Developer's tools -> Memory and take a snapshot after every click on IM1, IM2 you'll see the memory keeps increasing.

**Comment by dannyrb** [comment]
Thanks for this. I'll add this to my list of things to take a look at. I'll try to host an example for others to play with as well, and post that here when I'm able.

**Comment by agustingrigoriu** [comment]
Sorry to bother, but have you made some progress on this matter?

**Comment by dannyrb** [comment]
I'm playing locally with the example @leonardorame provided. I'm having some interesting results where, when I remove `cornerstone-tools`, if I toggl

**Comment by leonardorame** [comment]
So, the problem seems to be cornerstone-tools?

**Comment by dannyrb** [comment]
@leonardorame, it _could_ be, but I've really just started looking. I'm not sure what `cornerstone-tools` could possibly be doing that would cause that memory spike. I'll have better answers for you after some more testing.

Just curious, why do you call `cornerstone.draw(element)`? You should be good to use just `cornerstone.displayImage(element, dicomImage)`?

**Comment by leonardorame** [comment]
> Just curious, why do you call cornerstone.draw(element)? You should be good to use just cornerstone.displayImage(element, dicomImage)?

I don't know it was an example created by @agustingrigoriu.

**Comment by leonardorame** [comment]
Hi @dannyrb, did you find something about the cause of the memleak?.

**Comment by swederik** [comment]
I just tested this with the latest versions and the example above and I am not seeing any increase in memory usage. Are you still seeing this issue?

**Comment by dannyrb** [comment]
This issue has been open for quite some time. If you're still experiencing issues and have an example that demonstrates as much, please feel free to comment and I will reopen.

We're in the process of rounding up memory, codec, and other common issues 👍

**Comment by wakahiu** [comment]
I've been seeing the memory leak on our webapp as well. Memory leak is not as noticeable for small images such as xrays but becomes a huge concern for larger images such as CT scans. You can also see the issue on MD.ai,s webapp. When you load CT images and take a heap snapshot, it's size continues to increase in an unbounded fashion until the webpage becomes too slow to be useable.

**Comment by dannyrb** [comment]
@wakahiu, a minimal reproduction in an isolated repo would go a long way towards addressing this issue. If you have the time to set one up, please feel free to create a new issue with the necessary information.

**Comment by chenxxcc** [comment]
> @wakahiu, a minimal reproduction in an isolated repo would go a long way towards addressing this issue. If you have the time to set one up, please feel free to create a new issue with the necessary information.

I also encountered this problem. When loading DR and MR, it seems that there is no problem, but when loading CT images (3000 + images), memory will always increase until chrome crashes.

**Comment by dannyrb** [comment]
Please create a new issue with a minimal reproduction

**Comment by DMIAOCHEN** [comment]
@dannyrb i found there is memory leak on XMLHttpRequest，i google so long time and find it can be better like this:
```javascript
// handle response data
    xhr.onreadystatechange = function (event) {
      // Action
      if (options.onreadystatechange) {
        options.onreadystatechange(event, params);

        return;
      }

      // Default action
      // TODO: consider sending out progress messages here as we receive the pixel data
      if (xhr.readyState === 4) {
        if (xhr.status === 200) {
          resolve(xhr.response, xhr);
        } else {
          // request failed, reject the Promise
          reject(xhr);
        }

        // release xhr
        xhr.onloadstart = nofunc;
        xhr.onloadend = nofunc;
        xhr.onreadystatechange = nofunc;
        xhr.onprogress = nofunc;
        xhr = null;
      }
    };
```

and nofunc

```javascript
function nofunc () {};
```

**Comment by dannyrb** [comment]
@DMIAOCHEN, can you create a new issue with your findings? Have you identified anything specific within the current implementation that causes a leak?

**Comment by DMIAOCHEN** [comment]
I did find a problem last week. I set the cache to 50 M and then repeatedly downloaded the file. I found that javascript memory remained unchanged at 50 M, but chrome memory footprint has been rising.

But I won't be able to reproduce it this week. :cold_sweat: :cold_sweat:

If I find something new later, I'll bring up another issue

**Comment by TonThana** [comment]
Good day,

I have noticed similar problem with the loading of DICOM images although I'm not quite certain due to inexperience in this area. 
As I was following the example from Example of displaying a DICOM P10 from the local file system [https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html] I noticed that as I re-upload a new set of DICOM series, the memory usage (as profiled by Chrome dev tool) kept increasing.

![image](https://user-images.githubusercontent.com/40159068/72261653-cee65180-3647-11ea-89f8-ac4acbed5140.png)

Notice that under Profiles, each snapshot is taken after I uploaded a new set of image (1st set ~130Mb, 2nd and 3rd ~300Mb ).
Also under Summary -> system/ JSArrayBufferData, several buffers were retained.

**Comment by andrei0807** [comment]
![image](https://user-images.githubusercontent.com/32348752/83400842-2ab64900-a436-11ea-8a93-0a88f37e8579.png)
![image](https://user-images.githubusercontent.com/32348752/83400884-3dc91900-a436-11ea-918b-7633e73eb223.png)
GPU and RAM leak are very large!!!

**Comment by dannyrb** [comment]
I'm sorry, but this is not enough information to be helpful.

**Comment by daron1337** [comment]
Hi guys, I've noticed the same issue. I've been using cornestone for years but with small images it's hard to detect thememory leak.

I ran into it a few days ago while playing with the [official cornerstone multiframe example](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/examples/wadourimultiframe/index.html).

Instead using the data provided in the example (80kb, 2 frames), change url and use [this one](https://test-data.r1-it.storage.cloud.it/MultiFrame_Anon.dcm).
It's an anonymized cardiac angiogram (https://www.medicalconnections.co.uk/Sample-Images/)

As you can see, the memory increases (400mb) every time the frame changes.
It's not cornerstone tool, the playClip tool simply calls `loadImage` .
It's not cornestone imagecache (you can set the cache to 0 manually with `imageCache.setMaximumSizeBytes(0)`).

It seems that every time loadImage is called old typed arrays are still in memory and/or garbage collector is not able to clean the old arrays.

Any suggestion? Thanks!

**Comment by KeQianWang** [comment]
> Hi guys, I've noticed the same issue. I've been using cornestone for years but with small images it's hard to detect thememory leak.
> 
> I ran into it a few days ago while playing with the [official cornerstone multiframe example](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/examples/wadourimultiframe/index.html).
> 
> Instead using the data provided in the example (80kb, 2 frames), change url and use [this one](https://test-data.r1-it.storage.cloud.it/Multiframe_Anon). It's an anonymized cardiac angiogram (https://www.medicalconnections.co.uk/Sample-Images/)
> 
> As you can see, the memory increases (400mb) every time the frame changes. It's not cornerstone tool, the playClip tool simply calls `loadImage` . It's not cornestone imagecache (you can set the cache to 0 manually with `imageCache.setMaximumSizeBytes(0)`).
> 
> It seems that every time loadImage is called old typed arrays are still in memory and/or garbage collector is not able to clean the old arrays.
> 
> Any suggestion? Thanks!

I also encountered this problem recently. The data of multiple frames of ultrasound has caused the browser memory to keep rising. Is there any solution?

> Hi guys, I've noticed the same issue. I've been using cornestone for years but with small images it's hard to detect thememory leak.
> 
> I ran into it a few days ago while playing with the [official cornerstone multiframe example](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/examples/wadourimultiframe/index.html).
> 
> Instead using the data provided in the example (80kb, 2 frames), change url and use [this one](https://test-data.r1-it.storage.cloud.it/Multiframe_Anon). It's an anonymized cardiac angiogram (https://www.medicalconnections.co.uk/Sample-Images/)
> 
> As you can see, the memory increases (400mb) every time the frame changes. It's not cornerstone tool, the playClip tool simply calls `loadImage` . It's not cornestone imagecache (you can set the cache to 0 manually with `imageCache.setMaximumSizeBytes(0)`).
> 
> It seems that every time loadImage is called old typed arrays are still in memory and/or garbage collector is not able to clean the old arrays.
> 
> Any suggestion? Thanks!

I have also encountered this problem recently. The memory of the browser has been rising due to the ultrasonic multi frame data (200K, 100 frames). What is the solution?

**Comment by KeQianWang** [comment]
I have also encountered this problem recently. The memory of the browser has been rising due to the ultrasonic multi frame data (200K, 100 frames). What is the solution?

**Comment by nyacoub** [comment]
This is related to issue #71
