### ISSUE TITLE
Signed pixel data is handled improperly

### ISSUE THREAD

**Issue by kedmon** [cornerstonejs/cornerstoneWADOImageLoader#161]
Hello-

I think there is a bug in the handling of signed image data.

The attached zip file has a file that should display as the standard SMPTE test pattern.  In the screenshot, you can see that it looks "washed out" with no true blacks.  The stored pixel values range from -2048 to +2047. But the screenshot shows that the max stored pixel value was computed as 4095.

Looking at the code, I think the problem is an assumption that it can do min/max values on the raw data values.  But that's not true for signed data, which is stored using 2's complement representation. It needs to convert the raw data value to a signed data type before doing a min/max computation.

This problem shows up in the getMinMax function, but I think it also affects anyplace that is handling signed pixel data.

Thanks,
 -Kevin

![cornerstone signed data bug](https://user-images.githubusercontent.com/3640489/34539655-39b2a3a6-f086-11e7-9f93-520fa8dc95a4.png)

[vlut_06.zip](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/files/1601667/vlut_06.zip)

**Comment by dannyrb** [comment]
@swederik I was able to reproduce using the provided test image. Here is how the image is displayed in my desktop viewer: https://www.screencast.com/t/mOya4bjKy8C

**Comment by swederik** [comment]
This may have been fixed by: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/168

I'm going to add a test case to check that.

**Comment by malaterre** [comment]
@swederik I believe this bug can be closed. Here is what I see today:

![image](https://user-images.githubusercontent.com/228803/77897564-19a45c80-727a-11ea-859c-8557cccd9314.png)

**Comment by swederik** [comment]
Thanks for checking!
