### ISSUE TITLE
The file cornerstoneWADOImageLoader.min.js refers non minified Codecs and WebWorker files

### ISSUE THREAD

**Issue by andreiropotica** [cornerstonejs/cornerstoneWADOImageLoader#167]
`webWorkerPath:"../../dist/cornerstoneWADOImageLoaderWebWorker.js",webWorkerTaskPaths:[],taskConfiguration:{decodeTask:{loadCodecsOnStartup:!0,initializeCodecsOnStartup:!1,codecsPath:"../dist/cornerstoneWADOImageLoaderCodecs.js"`

**Comment by swederik** [comment]
Closing because 3.0.0 no longer has these as separate files.

Thanks!
