### ISSUE TITLE
Invalid Typed array length

### ISSUE THREAD

**Issue by algates90** [cornerstonejs/cornerstoneWADOImageLoader#170]
Getting the below error while calling cornerstone.loadandcacheimage.

![image](https://user-images.githubusercontent.com/30894700/35990241-b92b3c62-0d03-11e8-8be3-6715b0df71bb.png)

Is it possible to catch the error ?

**Comment by dannyrb** [comment]
That's odd.

- Are there any specific steps I can follow to reproduce this?
- What version of each Cornerstone library are you using?
- Does this happen for _all_ images, or specific images?
- Can you include an example code snippet?

Bonus points for a reproducible example in Codepen.

**Comment by algates90** [comment]
A normal cornerstone.loadandcacheimage function will throw up this error based on the file.

This does not happen with all dicoms. It happens with few corrupt dicoms. But these dicoms are still readable by MicroDicom viewer and other viewers though  the pixels are not proper. 

So there must be a way to capture this error when it happens or another separate function which reads if the file is good or bad before calling loadandcacheimage.

cornerstone core - 0.11.0
cornerstone-wado-image-loader - 0.14.6

**Comment by dannyrb** [comment]
It looks like you are two major versions behind. Are you able to branch and test using the latest versions to see if the issue persists? Depending on the size of your project, updating to latest may require some work.

**Comment by chafey** [comment]
The philosophy of cornerstone is to enforce 100% standards compliance by default but provide mechanisms for developers to workaround standard violations if they choose.  This philosophy is to provide more visibility to standard violations rather than hide them like other viewers do

**Comment by dannyrb** [comment]
@algates90, if you have anonymized images that produce these errors in the latest version, please feel free to add them to this issue. I intend to do a round up here soon of test cases that we can build tests against and fail gracefully or fix.
