### ISSUE TITLE
There is no friendly way of specifying Auth or custom headers

### ISSUE THREAD

**Issue by Saucistophe** [cornerstonejs/cornerstoneWADOImageLoader#177]
We have an in-house wado server, and it requires user authentication and authorization to ensure the user has the right to see the requested images.

Putting the Auth info in the URL is both insecure (since it will be logged on the client and server side) and impratical (changing the value screws up the loader's index, and it queries the images all over again).

I propose putting a section for additionalHeaders in the loadAndCacheImage's options; so that it will be passed on to the loader. I would gladly create a Pull Request with such a modification!

**Comment by dannyrb** [comment]
I had to do some digging, but I think this is already supported. Check out:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/bb8d9777ccc91de5daaaae2d478e1f14482159ec/examples/wadouri/index.html#L186-L191

And

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/bb8d9777ccc91de5daaaae2d478e1f14482159ec/examples/wadors/index.html#L94-L102

Let me know if these don't do the trick. Also, if these do work for you, I'd be happy to accept a PR to update documentation on this.

**Comment by Saucistophe** [comment]
Works as a charm. I'll add a PR! Many thanks!

**Comment by gillib** [comment]
This is critical for me, I store the dcm files in amazon's aws s3 storage and I need to add auth headers as well

**Comment by erasromani** [comment]
Can you please share how exactly one should add accessKeyID and secretKey to the template listed in https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/bb8d9777ccc91de5daaaae2d478e1f14482159ec/examples/wadouri/index.html#L186-L191 if I am trying to use a private aws s3 bucket with cornerstoneWADOImageLoader?
