### ISSUE TITLE
'cornerstoneWADOImageLoaderWebWorker' does not work, 'window is not defined'

### ISSUE THREAD

**Issue by sculxp** [cornerstonejs/cornerstoneWADOImageLoader#189]
try example  'customWebWorkerTask'

This bug is related to webpack, please read this:
https://github.com/webpack/webpack/issues/6677

**Comment by hanhanhan** [comment]
me too

**Comment by fcortes** [comment]
While this is not a real fix, you can make it work by adding `var window = self;` at the top of the generated cornerstoneWADOImageLoaderWebWorker.js

**Comment by galelis** [comment]
Hey guys,

Sorry the missing feedback, I have pushed a fix on latest version of cornerstoneWADOImageLoader, if you guys can please check if thats working. 

I also published a new release version (cornerstone-wado-image-loader@2.1.1)

**Comment by dannyrb** [comment]
This appears to be working. Thanks, @galelis! If anyone is encountering a similar issue I recommend opening a new ticket.
