### ISSUE TITLE
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode

### ISSUE THREAD

**Issue by jcorry5** [cornerstonejs/cornerstoneWADOImageLoader#193]
Hello, 

Currently trying to build a web application to view Dicom files from a local drive, when opening the file, the DICOM data is being parsed and returning information, but pixel data is not being returned instead giving this error. 

Using the live examples to open the Dicom files I have work with no problems.

**Comment by jcorry5** [comment]
![capture](https://user-images.githubusercontent.com/35064414/39063204-1a0b939c-44c2-11e8-8cb3-ec4045e13bad.PNG)
![capture2](https://user-images.githubusercontent.com/35064414/39063211-20ed3cc4-44c2-11e8-91f0-8b2b6a3e97be.PNG)

**Comment by dannyrb** [comment]
This issue has been around for quite a while so I'm going to close it. My best guess is that this issue resolves itself if you use a local webserver to serve up the client and assets.

If you're still having issues, please feel free to comment here and I'd be more than happy to re-open this.
