### ISSUE TITLE
cornerstoneWADOImageLoaderWebWorker Upgrade

### ISSUE THREAD

**Issue by Delink-D** [cornerstonejs/cornerstoneWADOImageLoader#198]
When I use the latest cornerstoneWADOImageLoaderWebWorker https://unpkg.com/cornerstone-wado-image-loader@2.1.1/dist/cornerstoneWADOImageLoaderWebWorker.js to load my dicom files in cornerstone I get a warning that 'smallest / largest pixel values are incorrect' on the console and a blank/black image is displayed. 
What could be the issue with the latest cornerstoneWADOImageLoaderWebWorker or what could I be missing

**Comment by AntoineLambricht** [comment]
I have the same warning and but black image is displayed for me.

**Comment by Delink-D** [comment]
I meant black image

**Comment by leesei** [comment]
Temporary fix is to add `strict: false` to `decodeConfig.decodeTask`.
