### ISSUE TITLE
bug for version 2.1.2

### ISSUE THREAD

**Issue by hu3402379** [cornerstonejs/cornerstoneWADOImageLoader#204]
Hi, I think there is a bug for new version 2.1.2.

When i use cornerstoneWADOImageLoader 2.0.0 version, the default viewport is normal. but when i update to version 2.1.2,  some strange things happened.

The core code is as follows:

> cornerstone.**loadAndCacheImage**(imageId).then((image) => {
                // Get the default viewport
                if (!viewport) {
                    viewport = cornerstone.getDefaultViewport(element, image)
                    console.log(viewport)
                }
            )}

When I first load the image， the viewport is normal, console log like this:

> colormap:undefined
displayedArea:{tlhc: {…}, brhc: {…}, rowPixelSpacing: 0.486328125, columnPixelSpacing: 0.486328125, presentationSizeMode: "NONE"}
hflip:false
invert:false
labelmap:false
modalityLUT:undefined
pixelReplication:false
rotation:0
scale:NaN
translation:{x: 0, y: 0}
vflip:false
**voi:{windowWidth: 1200, windowCenter: -600}**
voiLUT:undefined

and then I do something(not refresh page), and make it reload the image, the viewport console log like this:
>colormap:undefined
displayedArea:{tlhc: {…}, brhc: {…}, rowPixelSpacing: 0.486328125, columnPixelSpacing: 0.486328125, presentationSizeMode: "NONE"}
hflip:false
invert:false
labelmap:false
modalityLUT:undefined
pixelReplication:false
rotation:0
scale:NaN
translation:{x: 0, y: 0}
vflip:false
**voi:{windowWidth: 1906, windowCenter: 3812}**
voiLUT:undefined

the defalut ww/wc has been changed.

But if i use cornerstone.**loadImage**(imageId).then((image), not **cornerstone.**loadAndCacheImage****, the ww/wc is normal.

I guess this is due to changes in the version upgrade to some code, I have not found a solution。

**Comment by swederik** [comment]
That's odd.. What are image.windowWidth and image.windowCenter?

**Comment by hu3402379** [comment]
@swederik Thanks for your reply.
I can not understand what's your mean?
Forgive my poor English。。。

**Comment by hu3402379** [comment]
[imageConsole.zip](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/files/2092328/imageConsole.zip)
hi, attach file is console.log(image) screenshots。
sorry for my late reply.

**Comment by hu3402379** [comment]
@swederik Hi,first load image console like: 
![Aaron Swartz](https://raw.githubusercontent.com/hu3402379/images-for-reply/master/images/first-load.png)

and second reload console like:
![Aaron Swartz](https://raw.githubusercontent.com/hu3402379/images-for-reply/master/images/second-reload.png)

thanks.
