### ISSUE TITLE
How to read multiple  dicom  images at once ?

### ISSUE THREAD

**Issue by Im-Goutham** [cornerstonejs/cornerstoneWADOImageLoader#206]
Hi I want to know how we can read multiple dicom images with this library ? 
I want to implement a scroll of dicom images. 
I am able to read a single dicom file , but want to implement a scroll with multiple images.

**Comment by swederik** [comment]
You can look at https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/index.html for some inspiration.

Sounds like you want this: https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackScroll/index.html

**Comment by Im-Goutham** [comment]
This example is given with base64 images. 
I want to implement scroll for .dcm files.
