### ISSUE TITLE
viewer bug

### ISSUE THREAD

**Issue by jonnylee** [cornerstonejs/cornerstoneWADOImageLoader#208]
Sometimes Cornerstone cannot show the correct image, can you help me to solve this problem?

![image](https://user-images.githubusercontent.com/10759663/42417019-3702a75c-82b0-11e8-9cec-751c1e7c985c.png)
![image](https://user-images.githubusercontent.com/10759663/42417105-ae431a2a-82b2-11e8-98f2-7a378b3205b2.png)

**Comment by dannyrb** [comment]
Steps to reproduce? I see your input, but what interactions are you making, and what's the expected vs actual output?

**Comment by jonnylee** [comment]
dcm in other viewer:
![image](https://user-images.githubusercontent.com/10759663/42425094-51058576-834a-11e8-8e15-7fd477d340e7.png)

dcm in cornerstone:
![image](https://user-images.githubusercontent.com/10759663/42425122-ad19ce9e-834a-11e8-93a2-7e6c025626e4.png)

The function ww/wwc in these two files are not work.

**Comment by dannyrb** [comment]
Unchecking "Apply VOI LUT" returns the expected image:

![image](https://user-images.githubusercontent.com/5797588/42425372-93aa8df0-82ea-11e8-9f22-e64e78562f75.png)

Your image may have values you don't expect for VOI LUT:

![image](https://user-images.githubusercontent.com/5797588/42425385-a7bf1ff4-82ea-11e8-80c3-0fe821e9acca.png)

If you feel the VOI LUT values are not being applied correctly, please follow up. If that's the case, I'll need to flag someone else, as that's a bit outside my realm of expertise.

**Comment by jonnylee** [comment]
Thanks for your prompt reply.
You save my life.

**Comment by dannyrb** [comment]
@jonnylee I hope that means I answered your question? I'm going to mark this issue as closed.
