### ISSUE TITLE
Image largest Pixel Value

### ISSUE THREAD

**Issue by DreamerG** [cornerstonejs/cornerstoneWADOImageLoader#218]
error:Image smallestPixelValue tag is incorrect. Rendering performance will suffer considerably.
The rendered canvas is black and has no image information. The warnings reported by the browser are as above.

**Comment by liy9426** [comment]
I have the same issue here

**Comment by swederik** [comment]
Can you post an anonymized copy of the image?

**Comment by DreamerG** [comment]
Thank you for your attention.



I was thinking that the .dcm file was not rendered successfully because the values of the two variables marked in the image are undefined.
So I assign a value to image.maxPixelValue in the callback function of the loadAndCacheImage method.
I found that by increasing this value, the file is gradually rendered more clearly.
Later I modified the file cornerstoneWADOImageLoaderWebWorker.js



Changed the condition, so that the statement is executed to the else branch, so that my canvas completely renders the dcm file.
------------------ 原始邮件 ------------------
发件人: "Erik Ziegler"<notifications@github.com>;
发送时间: 2018年9月11日(星期二) 下午3:05
收件人: "cornerstonejs/cornerstoneWADOImageLoader"<cornerstoneWADOImageLoader@noreply.github.com>;
抄送: "DreaMer丶"<501800266@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cornerstonejs/cornerstoneWADOImageLoader] Image largest PixelValue (#218)




Can you post an anonymized copy of the image?

**Comment by dannyrb** [comment]
Duplicate: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/220
