### ISSUE TITLE
bad request

### ISSUE THREAD

**Issue by vsaase** [cornerstonejs/cornerstoneWADOImageLoader#219]
Hi,
I am seeing an Status 400 Bad Request response because of the quotes around application/octet-stream in this line of code

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/a461c7518bfc7c80b3b092a6ef0303df04a67428/src/imageLoader/wadors/loadImage.js#L49

**Comment by vsaase** [comment]
Well, that may be, but I am using just Orthanc as the server. 
It seems to either be a bug in `xhr.setRequestHeader(name, value)` when value contains quotes or with the Orthanc server.
When copying the request from the browser and running it with curl it only works if I remove the quotes.

**Comment by chafey** [comment]
That means its a bug in orthanc
