### ISSUE TITLE
About performance problem?

### ISSUE THREAD

**Issue by xingbofeng** [cornerstonejs/cornerstoneWADOImageLoader#221]
I use cornerstone build my application.Decoding Image is a problem.I try to use all decode algorithm, for example:jpeg-ls,jpeg-2000.It cost time and memory so much, I think.I konw asm.js with performance problem.how about Web Assembly? Do you think to use Web Assembly should enhance the performance, if it, I just want to try...

**Comment by dannyrb** [comment]
@xingbofeng I'm not sure that Web Assembly is "main stream" enough for us to spike it as a potential solution. If you want to take a stab, I would be very interested in your results and implementation.

A potential workaround would be converting the images to a different/consistent format server side before they're processed by the `cornerstoneWADOImageLoader`. This way, you don't need to load as many codecs, and you can choose the one that is the most performant for the web client to decode.

**Comment by xingbofeng** [comment]
thanks, I had tried to covert images server side.For example, I found that with the `JPEG-LS Lossless Image Compression` cost so much memory, so I change decode algorithm to `JPEG Lossless` by converting the images `transfer syntax` to `1.2.840.10008.1.2.4.70`.However, it cost so much time......What kind of decoding method as you thought is the best method to use, with the balance of time and memory?

**Comment by dannyrb** [comment]
@xingbofeng doing the conversion on-demand will have a very high resource and time cost. When we receive DICOMs from imaging modalities, we convert them as they're received. This means we're persisting more data (the original and a converted copy), but the network requests and decode time are much more timely.

**Comment by xingbofeng** [comment]
Thank you ! @dannyrb I will try it just with only one decoding method, so that I can load just one decoding method, for example, `transfer syntax 1.2.840.10008.1.2.4.70`, I load `jpeglossless.js`
