### ISSUE TITLE
Image can not be displayed in some browsers on Android platform

### ISSUE THREAD

**Issue by hu3402379** [cornerstonejs/cornerstoneWADOImageLoader#224]
Hi
I stumbled upon a bug today. I think there is a bug in some browsers, such as qq/uc browser(google is normal) on Android platform (If the dicom file is not compressed or by jpeg-2000 compressed, it is normal and can be displayed in any browsers). 
And the bug doesn't display in IOS platform.
[jpeg-ls.zip](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/files/2510292/jpeg-ls.zip)

### My dicom file is compressed by jpeg lossless

I have debug cornerstoneWADOImageLoader step by step, then i can not enter this function
(when taskType == 'decodeTask'):
###cornerstoneWADOImageLoaderWebWorker.js 

 ```// dispatch the message if there is a handler registered for it
  if (taskHandlers[msg.data.taskType]) {
    taskHandlers[msg.data.taskType].handler(msg.data, function (result, transferList) {
      self.postMessage({
        taskType: msg.data.taskType,
        status: 'success',
        result: result,
        workerIndex: msg.data.workerIndex,
          }, transferList);
    });
```

Maybe there is an error inside the hander method (I can't debug the internal method of the hander, so I am confused ).

If someone can use the browser test I mentioned on the Android platform, it should be easy to reproduce the problem.

This problem can only occur in some browsers (qq/uc etc.) on the Android platform.

I am confused, I don't know how to solve this problem.

The attachment is compressed by jpeg-ls and can be used for testing.

Thanks.

**Comment by dannyrb** [comment]
Hi @hu3402379. Can you create a small repo that reproduces this particular error? I'd be more than happy to pull it down and test it on our suite of android devices to see if I can reproduce.

**Comment by hu3402379** [comment]
@dannyrb  I have created a repo for android devices test.
This is  [test link](https://github.com/hu3402379/testForAndroid)

**Comment by hu3402379** [comment]
@dannyrb 
Thank you for taking the time to test。
I found that JPEG-LS decode takes up more memory than JPEG LOSSLESS during the testing in browser，and some android devices browser can not display JPEG-LS image。

So I think this problem can be turned off and i will find some way to get the exception from web work code if i am free.

Thanks a lot.
