### ISSUE TITLE
IE11 Object.assign - “Object doesn't support property or method 'assign'”

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstoneWADOImageLoader#234]
I've downloaded cornerstoneWADOImageLoader.js from this unpkg URL:

    https://unpkg.com/cornerstone-wado-image-loader@2.2.3/dist/cornerstoneWADOImageLoader.js

Everything works ok but on IE11 I'm getting `Object doesn't support property or method 'assign'`.

This is caused because the `loadImage` function uses `Object.assign`, and aparently Babel is not taking care of it:
 
```
function loadImage(imageId) {
  var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  var parsedImageId = Object(_parseImageId_js__WEBPACK_IMPORTED_MODULE_1__["default"])(imageId);
  options = Object.assign({}, options);
  var loader = options.loader;
  ...
```
Any workaround?.

**Comment by dannyrb** [comment]
I'm not sure what we target. You can always polyfill:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

**Comment by leonardorame** [comment]
Yes, but this shouldn't be handled automatically by Babel?.

**Comment by leonardorame** [comment]
Well, the workaround was appending this code in my `index.html`:

```:javascript
 (typeof Symbol === "undefined") {                                                                      
          var script = document.createElement('script');                                                        
          script.type = 'text/javascript';                                                                      
          script.src = 'https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.0.0/polyfill.min.js';           
          document.getElementsByTagName('head')[0].appendChild(script);                                         
      }  
```

**Comment by dannyrb** [comment]
In general, library authors shouldn't include polyfills. Imagine if 10 of your dependencies included the same polyfill? It would be unnecessary bloat. Instead, the consumer can choose which polyfill to use, and when to use it.

I don't recall our exact transpilation target/support, but that's the gist.
