### ISSUE TITLE
Issue Running Examples

### ISSUE THREAD

**Issue by Neuroforge** [cornerstonejs/cornerstoneWADOImageLoader#242]
Hello,

I am following the instructions from here, i wish to run the examples locally.

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/docs/Building.md

<img width="682" alt="screen shot 2019-02-15 at 7 43 46 pm" src="https://user-images.githubusercontent.com/1474186/52839179-07408f80-315a-11e9-8571-a2547af32529.png">

The project just hangs here when running npm run watch as per the screen shot. What dumb mistake am i making?

1) Checkout repo.
2) cd to repo
3) npm install
4) npm run build
5) npm run watch

Regards,

Daniel

**Comment by swederik** [comment]
Hmm it doesn't look like you are doing anything wrong. `watch` just sits and waits for changes to rebuild the library. If you want to see the examples, run a webserver and go to /examples/index.html folder. You can try with `python -m SimpleHTTPServer 3000` in the repo root.

Sorry for our lack of clear documentation... We are happy to take PRs to improve the docs.

**Comment by dannyrb** [comment]
@Neuroforge, was this issue resolved by a recent change?
