### ISSUE TITLE
Use WebPack's worker-loader to improve DX

### ISSUE THREAD

**Issue by xingbofeng** [cornerstonejs/cornerstoneWADOImageLoader#244]
when I use cornerstoneWADOImageLoader, I find that I meet cross domain problem so that I must use proxy to solve this problem. but use [worker-loader](https://github.com/webpack-contrib/worker-loader) , web worker can be translated to Blob Object so that not corss domain problem.Why not use worker-loader to load cornerstoneWADOImageLoaderWebWorker ? If it's OK, I can create a pull request.

**Comment by swederik** [comment]
Hello! Thanks for the suggestion.

Yes this could be a much more user-friendly solution, I'd be interested to try this approach if you are willing to undertake the work.

I kinda hate the fact that we have to serve the workers / codecs separately right now in each app we support. Sometimes they get out of sync with the library version, other times you can't find them from the right path, etc. We just haven't had the bandwidth to look into improving this approach.

**Comment by dannyrb** [comment]
I'm a huge fan of `worker-loader`. In my team's fork of `cornerstoneWADOImageLoader`, that's what we use. If you create a PR, I would be more than happy to review it.

I'll mark this issue as an enhancement. If you wish to discuss specifics further, please feel free to do so.

**Comment by xingbofeng** [comment]
@dannyrb Ohh...yesterday, I trid to add worker-loader to cornerstoneWADOImageLoader, worker-loader, I set the config of worker-loader to `options: { inline: true, fallback: false }`, the in cornerstoneWADOImageLoader, the web-worker translated to Blob Object, but made me so sad...because of the cornerstoneWADOImageLoaderWebWorker.js is large...JavaScript Stack is overflow...

**Comment by dannyrb** [comment]
Ahh! That's interesting. I'll see what we're doing differently to get around that issue in our own code base. Thanks for the update!

**Comment by swederik** [comment]
Added in #264. Released 3.0.0 because this is a breaking change.

Thanks!
