### ISSUE TITLE
Expose webWorkerManager's webWorkers

### ISSUE THREAD

**Issue by talkdirty** [cornerstonejs/cornerstoneWADOImageLoader#246]
Displaying DICOM images is only necessary in some parts of my application. Is there a way to obtain a reference to the active workers so I can `.terminate()` them when I no longer need them?

**Comment by dannyrb** [comment]
I'm not sure we expose the Worker references that are stored here:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/webWorkerManager.js#L10

I think the only way to do it, currently, would be to add a "terminateWorker" task, and queue up the tasks for the workers to terminate themselves.

I'd be open to a PR that makes all of this a little easier.

**Comment by talkdirty** [comment]
Thanks! Alternatively, would you be open to exposing `webWorkers` to the interface of `webWorkerManager`?

**Comment by swederik** [comment]
Yeah that sounds like a good fix to me

**Comment by dannyrb** [comment]
@talkdirty, if you make the PR, I will review it 👍

**Comment by talkdirty** [comment]
Thanks @dannyrb! I had a go here: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/248

**Comment by dannyrb** [comment]
Merged: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/248

We don't yet leverage `semantic-release` in this Repository, so you'll need to wait for the next manual release to be cut for these changes to become available.
