### ISSUE TITLE
RLE lossless is not loading properly with pixelformat == 3

### ISSUE THREAD

**Issue by niks2060** [cornerstonejs/cornerstoneWADOImageLoader#255]
I am trying to draw an RLE lossless image in canvas but it is not rendering properly,

I think issue is in decode16 but not able to find 

![temp1](https://user-images.githubusercontent.com/11830418/55721398-eb05f400-5a20-11e9-921a-0ac85e83a481.png)

**Comment by malaterre** [comment]
Are you doing Segmentation (1bit image) ?

**Comment by dannyrb** [comment]
@niks2060, I can't mark this as a bug without a way to reproduce the issue, and a verified working result in a known good viewer. Generally Osirix, Horos, or RadiAnt will do.

**Comment by niks2060** [comment]
It's was resolved. Sorry I am not working on this dicom anymore and I forgot to close this .
