### ISSUE TITLE
DICOM file can not be displayed and is shown as blank image

### ISSUE THREAD

**Issue by kalki** [cornerstonejs/cornerstoneWADOImageLoader#257]
Hello,

I got a DICOM which can not be displayed in cornerstone and it shows as a blank image and there is not error message in browser console.

It can be reproduced in example "dicomfile (DICOM P10 on local file system)" at 
https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

When I load the DICOM file in this example page, it just displays a complete white image.  And there is no notable error message in console.

The DICOM file can be displayed correctly in a native DICOM viewer like MicroDicom viewer.

Here is screen shot for CornerstoneWADOImageLoader Example with that DICOM file loaded
![02](https://user-images.githubusercontent.com/3347264/56755948-4119bc00-67c3-11e9-8727-ec21c259cc7e.png)

Here is screen shot for native program with that DICOM file loaded
![01](https://user-images.githubusercontent.com/3347264/56755984-5e4e8a80-67c3-11e9-9623-49819d4b21dd.png)

Here is the DICOM file with problem
[file0.zip](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/files/3118151/file0.zip)

**Comment by kevinleedrum** [comment]
It has something to do with the VOI LUT because unchecking "Apply VOI LUT" fixes the render so it matches your other screenshot.

**Comment by kalki** [comment]
Just examined the DICOM file and maybe it contains incorrect data.

The file has an empty VOI LUT Sequence (0028,3010) and has no LUT Descriptor(0028, 3002) or LUT Data (0028, 3006). As result, the image object loaded has an invalid voiLUT object { firstValueMapped: undefined, id: "1", lut: [], numBitsPerEntry: undefined} and that cause display error.

Set voiLUT of viewport to undefined resolves the problem.

Thanks a lot for help.
