### ISSUE TITLE
Google Browser Crash

### ISSUE THREAD

**Issue by chenxxcc** [cornerstonejs/cornerstoneWADOImageLoader#263]
I also had a memory overflow problem. When loading DR and mr, it seems no problem, but when loading CT images (more than 3000 images), memory will increase until chrome crashes.

**Comment by dannyrb** [comment]
We've had misc. reports of this. I've found that periodically killing the workers and spinning them back up can buy you some wiggle room as a temporary fix. If we had a good reproduction that could help us isolate the issue, it would go a long way.

I have a long bucket list of improvements I would like to see for this library. I have a sneaking suspicion that some of them around codecs may resolve this issue.
