### ISSUE TITLE
cornerstoneWADOImageLoader failed to load a set of dicom

### ISSUE THREAD

**Issue by longerking** [cornerstonejs/cornerstoneWADOImageLoader#286]
I am using cornerstoneWADOImageLoader to load my dicom from orthanc, but I am new to cornerstone.  
I successed to load a dicom file by setting imageId, then I tried to load a series of dicom by setting imageId as an array and wanted to preview them on enableElement by mouse scrolling.  Obviously, I failed.
So how to display a set of dicom?
Appreciate any response!

Here is my vue.js code
```vuejs
        mounted () {
            // const imageId = " wadouri:http:http//127.0.0.1/data/1.dcm";
            const imageId = [
                              "wadouri:http:http//127.0.0.1/data/1.dcm",
                              "wadouri:http:http//127.0.0.1/data/2.com",
                               "wadouri:http:http//127.0.0.1/data/4.dcm",
                               "wadouri:http:http//127.0.0.1/data/5.com",
                            ];
            this.loadAndViewDicom(imageId);
        },
        methods: {
            loadAndViewDicom(imageId) {
                const element = this.$refs.cornerstoneCanvas;
                cornerstone.enable(element);
                cornerstone.loadAndCacheImage(imageId).then(
                    (image) => {
                        cornerstone.displayImage(element,image);
                    },
                    (err) => {
                        console.error(err);
                    }
                );
            },
       }
```

**Comment by chafey** [comment]
Your imageid's are not correct, see documentation here for examples:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/docs/ImageIds.md

**Comment by chafey** [comment]
Also - make sure that the URL you are using is actually returning DICOM P10 using CURL or postman first

**Comment by longerking** [comment]
Than you @chafey .
I have used the correct ImageId.
```vuejs
const imageId = "wadouri:http://127.0.0.1:8042/instances/8a327cd3-08cb5ede-20364c8c-01a0139b-cdbd2282/file"
```
Through CURL in postman, DICOM file has been returned.
But when running the correct imageId in my code, It return the following error:

**dicomParser.readPart10Header: DICM prefix not found at location 132 - this is not a valid DICOM P10 file.**
I can correctly view this dicom file by using Orthanc dicom-web.

It seems that *dicomParser* dose not work or this dicom file is not DICOM P10.
Whether *cornerstoneWADOImageLoader* can only load *DICOM P10* file?

**Comment by longerking** [comment]
Thanks! I have solved this problem.
https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/tools/stack-scroll-mouse-wheel.md

**Comment by acegank** [comment]
@longerking  can you tell me how to solved this problem？

**Comment by longerking** [comment]
> @longerking can you tell me how to solved this problem？

define the stack const stack = { currentImageIdIndex: 0, imageIds }

**Comment by acegank** [comment]
@longerking 大哥知道segmentation怎么导出png吗
