### ISSUE TITLE
401 Unauthorized : while accessing image file from server folder 

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstoneWADOImageLoader#289]
while loading below url I am getting 401 error
**http://localhost:35360/App.Service/CommonFiles/bbmri-53323851**

in the cornerstoneWADOImageLoader.configure i am passing this parameter 

 ```
cornerstoneWADOImageLoader.configure({
        beforeSend: function(xhr) {
            // Add custom headers here (e.g. auth tokens)
            const apiKey = 'Bearer: WxVlvpBY4wYqSe-S_sfwXy7kxTd4u1Xk_OHIcV8YBMjtmyBAIDIKxXxfZs_pRaVU2sILLSy6qH8ZQy5yXcBUMaUvaiyXbcW-pyn9LB1o-EJcO2i33-adX468Eq6v_D3qO9hThVX7bOpX-P9z7_5Jk7DRG_75tZG-UbdEUcSFrvF0FjULdFyjhLeqdILxYd1j5705rv5CX8zl5BEqvZ3PLLwfdpKsAyTmJ2O3YXGVpk0uZLYKICH-joUhZlDCgR69kXG1E7DLtfnr7zwDfknFfm2qLgr8tl1M91iT4TzN71CNYD9fh2FaU9OAc1yZERBwiOGSpbr5E_A7vf3k0qPbaFS-tvD_KBJYYOxTawNpBCrLkwGYKYTDATRDLO3SREDhxSvUaWTnBNPdfKW8e9J8EXN4XZXz7ZocRBa0BHAwxFpc5iLIz2aOemTosZmRFFbAFXPqbSWEAIhIY8dXjwJlaRhZhIYxgsOBTj5kUG3_3Km1oKSUlFLvZaineU0fZjl2dj1rEas9icUho6tbNbRuIVpCmdfvYZKL0p5xXfVr0jloNM-WVbh6OCaW-cgCKQhIfDGkeisAGqAcqXxN5Rpeqon2xvbvE9GwZ96a9vLuBzVtdsa-0FIfRCfWj8GnB9tHpO7pOZ1XdSTh-o-oueRHng942WcWJqpWlehJrbaHsWsVzY-BaHAlbRmXlQ0p1TutbT5PCtWBoE4oWbXVQ3BDAuR-v1_vaY0ERTCDLA5wwVgaRZ8_';
			   
            if(apiKey && apiKey.length) {
                xhr.setRequestHeader('APIKEY', apiKey);
				xhr.setRequestHeader('content-type', 'application/dicom');
            }
        }
    });

	const baseUrl = 'http://localhost:35360/App.Service/CommonFiles/'
	const series = [
		'bbmri-53323851'
	]
const imageIds = series.map(seriesImage => `${scheme}:${baseUrl}${seriesImage}`);
var element = document.querySelector('.cornerstone-element');
cornerstoneTools.init();

cornerstone.enable(element);
cornerstone.loadImage(imageIds[0]).then((image) => {
  cornerstone.displayImage(element, image)
})
```
this is my code what is I am missing in it.

**Comment by dannyrb** [comment]
When you inspect the outbound request in your browser's inspector's network tab, do you see the expected headers and values set?

**Comment by pmd23** [comment]
> When you inspect the outbound request in your browser's inspector's network tab, do you see the expected headers and values set?

![image](https://user-images.githubusercontent.com/2580866/69134246-2ef3c800-0add-11ea-87a0-4390d7eecf93.png)

**Comment by dannyrb** [comment]
@pmd23, unfortunately I'm not sure what to tell you. The issue appears to be on your server's end. You're setting a header named `APIKEY` with a bearer token set. Servers often expect an `Authorization` header? Maybe you should consult the documentation of the solution you're integrating with.

**Comment by pmd23** [comment]
Thanks for reply...
so one question what is the **APIKEY**? should i prefer to allow access the server folder. My dicom images are stored into **CommonFiles** folder. so how I can access that. 
Or can you please guide any other way to configure the this things

**Comment by pmd23** [comment]
> @pmd23, unfortunately I'm not sure what to tell you. The issue appears to be on your server's end. You're setting a header named `APIKEY` with a bearer token set. Servers often expect an `Authorization` header? Maybe you should consult the documentation of the solution you're integrating with.

Thanks for the reply...
so one question what is the **APIKEY**? should i prefer as a apikey to allow access to the server folder. My Dicom images are stored into **CommonFiles** folder. so how I can access that.
Or can you please guide any other way to configure these things

**Comment by pmd23** [comment]
@dannyrb Yes man you correct its issue related to sever side which is from end. 
Thanks for such wonderful lib.
