### ISSUE TITLE
Can't resolve 'fs' in '..\node_modules\cornerstone-wado-image-loader\dist'

### ISSUE THREAD

**Issue by tostudypurpose** [cornerstonejs/cornerstoneWADOImageLoader#293]
On building my angular project I get this below error:
ERROR in ./node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js
Module not found: Error: Can't resolve 'fs' in '{project path}\node_modules\cornerstone-wado-image-loader\dist'.

package.json :

  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "cornerstone-core": "^2.3.0",
    "cornerstone-tools": "^4.8.0",
    "cornerstone-wado-image-loader": "^3.0.6",
    "cornerstone-web-image-loader": "^2.1.1",
    "dicom-parser": "^1.8.3",
    "file-system": "^2.2.2",
    "hammerjs": "^2.0.8",
    "npm-watch": "^0.6.0",
    "pako": "^1.0.10",
    "rxjs": "~6.4.0",
    "rxjs-compat": "^6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.19",
    "@angular/cli": "^8.3.19",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10"
  },
  "node": {
    "fs": "empty"
  }

My code is as follows:

```cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
cornerstoneWADOImageLoader.external.dicomParser = dicomParser;

var config = {
  maxWebWorkers: navigator.hardwareConcurrency || 1,
  startWebWorkersOnDemand: true,
};
cornerstoneWADOImageLoader.webWorkerManager.initialize(config);

export class ViewImageComponent implements OnInit {
  public imagePath;

  constructor(private router: Router, private route: ActivatedRoute) {
  }

  ngOnInit() {
    
      this.imagePath = "http://localhost/images/Abdomen.dcm";    

    cornerstoneWADOImageLoader.wadouri.dataSetCacheManager.purge();

    const element = document.querySelector(".image-canvas");

    let loadedImage;
    // Injects cornerstone "enabled" canvas into DOM
    cornerstone.enable(element);

    const imageID = cornerstoneWADOImageLoader.wadouri.fileManager.add(
      this.imagePath
    );

    cornerstone.loadImage(imageID).then(function(image) {
      console.log(image);
      loadedImage = image;
      cornerstone.displayImage(element, image);
    });

    cornerstoneWADOImageLoader.wadouri.fileManager.remove(imageID);
    }
}

**Comment by dannyrb** [comment]
duplicates: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/273
