### ISSUE TITLE
Get http://localhost:4200/undefined 404 (Not found) in cornerstoneWADOImageLoader.min.js:2 

### ISSUE THREAD

**Issue by iamZDspark** [cornerstonejs/cornerstoneWADOImageLoader#294]
Creating an angular project to load Dicom image which are hosted on virtual directory of IIS 10.0 , I have added a mime type for dicom files in my virtual directory, so now the dicom file is accessible.
In my angular I have written the code as:

```
import {Component,OnInit,Input,ElementRef,ViewChild,AfterViewInit} from "@angular/core";
import cornerstone from "cornerstone-core";
import cornerstoneMath from "cornerstone-math";
import cornerstoneTools from "cornerstone-tools";
import Hammer from "hammerjs";
import cornerstoneWebImageLoader from "cornerstone-web-image-loader";
import cornerstoneWADOImageLoader from "cornerstone-wado-image-loader";
import {Router,ActivatedRoute} from "@angular/router";
import {switchMap,map} from "rxjs/operators";
import dicomParser from "dicom-parser";

var config = {
	maxWebWorkers: navigator.hardwareConcurrency || 1,
	startWebWorkersOnDemand: true,
	taskConfiguration: {
		'decodeTask': {
			initializeCodecsOnStartup: false,
			usePDFJS: false
		},
		'sleepTask': {
			sleepTime: 3000
		}
	}
};

cornerstoneWADOImageLoader.webWorkerManager.initialize(config);
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
cornerstoneWADOImageLoader.external.dicomParser = dicomParser;

@Component({
	selector: "app-view-image",
	templateUrl: "./view-image.component.html",
	styleUrls: ["./view-image.component.css"]
})
export class ViewImageComponent implements OnInit, AfterViewInit {
      constructor(private router: Router, private route: ActivatedRoute) {
      }
ngOnInit() {
		
		const dicomPath = "http://localhost/images/Abdomen.dcm";  //Link of my dicom file

		const element = document.querySelector(".image-canvas");
		
		cornerstone.enable(element);
		cornerstone.loadImage("wadouri:" + dicomPath )	.then(image => {
			cornerstone.displayImage(element, image);
		}).catch(error => {
				console.error(error, error.data);
		});
            }
}
```

My HTML file is :
```
<div
      id="canvases"
      class="image-canvas-wrapper"
      oncontextmenu="return false"
      unselectable="on"
      onselectstart="return false;"
      onmousedown="return false;"
    >
      <div class="image-canvas" oncontextmenu="return false"></div>
    </div>
```

Versions which I am using are:

> "cornerstone-core": "^2.3.0",
    "cornerstone-math": "^0.1.8",
    "cornerstone-tools": "^4.8.0",
    "cornerstone-wado-image-loader": "^3.0.6",
    "dicom-parser": "^1.8.3"

But the image data is not getting displayed to my Element and on checking console I am getting error as : 
**Get http://localhost:4200/undefined 404 (Not found)   cornerstoneWADOImageLoader.min.js:2** 

Am I missing some configuration or how to resolve this issue?

**Comment by dannyrb** [comment]
`http://localhost/images/Abdomen.dcm` isn't wrapped in quotes? Does the URL return an image on your local machine? When debugging, does the error not occur until the `loadImage` call?

I'm not sure why you would get a `404` for a URL other than the one you passed in. I would also expect you to get a CORS error if the app and file are hosted at different ports?

**Comment by tostudypurpose** [comment]
> ORS error if the app and file are hosted at different ports

Sorry for dicomPath syntax, missed to add quote here, but in mine its already been added.

Yes while calling the URL returns image to me, I have already HTTP Response Header for "Access-Control-Allow-Origin" and its value as "*" for my virtual directory.
Addition to that I have added MIME types also for "application/dicom" and extension as "*dcm" in IIS Virtual Directory

On debugging there is no error till loadImage call. It calls loadImage method of cornerstone.js and then loadImageFromImageLoader() and I could see my imageLoaders as 
![image](https://user-images.githubusercontent.com/50664949/69629134-0c7c2480-1072-11ea-91d3-b83944f39fe5.png) and then calls loader() method and it hits to cornerstoneWADOImageLoader.min.js and returns imageLoadObject
![image](https://user-images.githubusercontent.com/50664949/69629794-772d6000-1072-11ea-8c60-d3da84c19107.png)

I have no clue where this thing is breaking for me

**Comment by tostudypurpose** [comment]
> `http://localhost/images/Abdomen.dcm` isn't wrapped in quotes? Does the URL return an image on your local machine? When debugging, does the error not occur until the `loadImage` call?
> 
> I'm not sure why you would get a `404` for a URL other than the one you passed in. I would also expect you to get a CORS error if the app and file are hosted at different ports?

Is there anything with the config and pattern of using config and loader which i should take into considerations?

**Comment by tostudypurpose** [comment]
I resolved my issue by changing config to:
```
var config = {
    webWorkerPath: '/assets/cornerstone/webworkers/cornerstoneWADOImageLoaderWebWorker.js',
    taskConfiguration: {
        'decodeTask': {
           codecsPath: '/assets/cornerstone/codecs/cornerstoneWADOImageLoaderCodecs.js'
        }
    }
}
```

Do we need to mention those all the time, isn't a way to not define path?

**Comment by dannyrb** [comment]
I don't believe you need to specify codecs at all in the latest major version
