### ISSUE TITLE
Dicom file not rendering correctly, for sop class 1.2.840.10008.5.1.1.30

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstoneWADOImageLoader#316]
Hi Team,
I working on dicom viewer in which there is some retired tag. I am really new to dicom viewer stuff. I have 1 dcm image with  SOP claass `'1.2.840.10008.5.1.1.30':'Hardcopy Color Image Storage SOP Class (Retired)'` in the some dicom viewer its showing correctly but while trying to load it using cornerstone its shows me weird.
<img width="1168" alt="upload" src="https://user-images.githubusercontent.com/2580866/81384401-3fe9d180-912f-11ea-9874-f19143cbbcc9.png">
 
My question is that how can i render it so that it will be render as correctly.

**Comment by leonardorame** [comment]
Here's a similar case, with a Secondary Capture image. Also tested using this: https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

![image](https://user-images.githubusercontent.com/1405017/92153899-5234fd00-edfb-11ea-8dce-30347450d1a9.png)

**Comment by DMIAOCHEN** [comment]
another slimilar case here:

**Comment by flyhuang** [comment]
I have read image loader source code,
```
function convertRGB(imageFrame, rgbaBuffer) {
  if (imageFrame.planarConfiguration === 0) {
    convertRGBColorByPixel(imageFrame.pixelData, rgbaBuffer);
  } else {
    convertRGBColorByPlane(imageFrame.pixelData, rgbaBuffer);
  }
}
```
it will convert rbg color by plane if dicom file have not set planarConfiguration tag (0028, 0006),  and i found many dicom device have not set this tag. 

i think most of dicom planarConfiguration should be "RGBRGBRGB" not "RRRRR....GGGGG....BBBBB", can we change the default planerCongfiguration to 0,

Can we change the function to 
```
function convertRGB(imageFrame, rgbaBuffer) {
  if (imageFrame.planarConfiguration === 1) {
    convertRGBColorByPlane(imageFrame.pixelData, rgbaBuffer);
  } else {
   convertRGBColorByPixel(imageFrame.pixelData, rgbaBuffer);
  }
}
```

@swederik  could u give me some suggestion?

**Comment by StevenRoger** [comment]
Is there anyone fixed this bug?
@swederik @flyhuang @DMIAOCHEN @pmd23

**Comment by StevenRoger** [comment]
I solved it by adding 'planarConfiguration' tag.

**Comment by flyhuang** [comment]
> Is there anyone fixed this bug?
> @swederik @flyhuang @DMIAOCHEN @pmd23

I have published a new package(cz-cornerstone-wado-image-loader) to fix this issue. this package also fix some wrong lut type config.

because these issue is caused by not-standard dicom file, so i have not create pr to cornerstone-wado-image-loader.

**Comment by leonardorame** [comment]
Thanks @flyhuang, where can we find the new package?

**Comment by flyhuang** [comment]
> Thanks @flyhuang, where can we find the new package?

https://www.npmjs.com/package/cz-cornerstone-wado-image-loader

@leonardorame
