### ISSUE TITLE
Increase in Bundle size when updating cornerstoneWadoImageLoader

### ISSUE THREAD

**Issue by priyankbhardwaj119** [cornerstonejs/cornerstoneWADOImageLoader#321]
Updated cornerstone-wado-image-loader from 2.1.2 to 3.1.2. Found a considerable increase in Bundle size after a prod Build. 1.45 MB to 4.3MB. (main.js)
What may be the reason for such an increase in file size?

**Comment by dannyrb** [comment]
The codecs are now in the bundle as opposed to a seperate bundle that is imported be each worker when spun up.

We agree that this is less than ideal. We will likely change the strategy near future when we update to consume more recent and more performant versions of the codecs.

**Comment by laozhu** [comment]
Is this repo [cornerstonejs/codecs](https://github.com/cornerstonejs/codecs) for sperating codecs from wado loader?
