### ISSUE TITLE
No color dicom getCanvas undefined

### ISSUE THREAD

**Issue by andersonscherrer** [cornerstonejs/cornerstoneWADOImageLoader#322]
Color images have getCanvas function that allow to getBlob image and download it as jpeg format. Why function getCanvas is not present when no color dicom file is loaded?

`if (image.color) {
        image.getCanvas = function () {
          if (lastImageIdDrawn === imageId) {
            return canvas;
          }

          canvas.height = image.rows;
          canvas.width = image.columns;
          var context = canvas.getContext('2d');
          context.putImageData(imageFrame.imageData, 0, 0);
          lastImageIdDrawn = imageId;
          return canvas;
        };
      } // Modality LUT`

**Comment by dannyrb** [comment]
I believe color 8-bit JPEGs have "getCanvas", because we use the browser's canvas element as our gateway to its built in encoder/decoder for images of that type.

We have to leverage other strategies for images encoded differently. I realize the lack of consistency in CornerstoneImage objects could be better documented.

Sent from my phone, so I hope this tackles the heart of your question.

**Comment by andersonscherrer** [comment]
Right, my workaround to get the other images to export to JPEG format, was to render in enabled cornerstone div, get this canvas, then get the Blob from it.

`cornerstone.loadImage("dicomweb:" + url).then(function (image) {

      if (image) {
        // COLOR imaga Have the getCanvas function
        if (typeof image.getCanvas === 'function') {
             image.getCanvas().toBlob(function (blob) {
                 resolve(blob);
             }, "image/jpeg", 1.0);
        } else {
          // no color images I workaround render its before I get rendered canvas
          var element = document.getElementById('dicomImage');
          element.hidden = false;
          var elementWidth = image.columns ? image.columns : 512;
          var elementHeight = image.rows ? image.rows : 512;
          element.style = "visibility: hidden; width:${elementWidth}px;height:${elementHeight}px;top:0px;left:0px;";

          cornerstone.enable(element);
          var viewport = cornerstone.getDefaultViewportForImage(element, image);
          cornerstone.displayImage(element, image, viewport);
         // I fixed 5s to wait cornerstone.displayImage but sametimes it take more time 
          setTimeout(() => {
            document.getElementsByTagName("canvas")[0].toBlob(function (blob) {
              element.hidden = true;
              resolve(blob);
            }, "image/jpeg", 1.0);
          }, 5000);
        }
      }
`

There is another way to do it?

**Comment by dannyrb** [comment]
If you're okay with an image that has pixel data that does not match the original, then your approach is the recommended one. For example, if you try to window level an image captured from the canvas that was originally a 16-bit grayscale, you will notice that finer details are now lost, hounsfield is incorrect, etc.
