### ISSUE TITLE
Which media types support cornerstoneWADOImageLoader for multiframe resquests?

### ISSUE THREAD

**Issue by pablovegaimexhs** [cornerstonejs/cornerstoneWADOImageLoader#330]
Hi cornerstone team!

I wanted to know: What media types do you support for multiframe resquests?

**Example:** jpeg, jis, jp2, jpx, dicom, etc.

![image](https://user-images.githubusercontent.com/67170659/89303132-61c0fa80-d631-11ea-8b27-a58c04c3e9f3.png)

Thanks in advance!

**Comment by chafey** [comment]
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/docs/TransferSyntaxes.md

**Comment by pablovegaimexhs** [comment]
Thanks a lot @chafey !
