### ISSUE TITLE
image.data is not set when using wadors

### ISSUE THREAD

**Issue by lambacini** [cornerstonejs/cornerstoneWADOImageLoader#336]
When loading images using wadors. getEnabledElement('imageid').image.data attribute is blank.
i know, we can access this attribute as dicompart10 because wadouri loads the entire dataset. Can dicomparser convert json to dataset?

**Comment by malaterre** [comment]
The WADO-RS example describe the mechanism you need to use instead:

* https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/wadors/index.html

See line:

```
               cornerstoneWADOImageLoader.wadors.metaDataManager.add(imageId, metadata);
```
