### ISSUE TITLE
[Help] Display Dicom in a <img src="">

### ISSUE THREAD

**Issue by GregdTd** [cornerstonejs/cornerstoneWADOImageLoader#355]
Hello everyone, hello @chafey,

I'm using `cornerstoneWADOImageLoader` and I can successfully display any dicom in my web app using this code:

```
const imageId = cornerstoneWADOImageLoader.wadouri.fileManager.add(currentFiles[0].data);

const element = document.getElementById('dicomCanvas');
cornerstone.enable(element);

cornerstone.loadImage(imageId).then((imge: any) => {
    cornerstone.displayImage(element, imge);
});
```

However, render in the web app is not enough in my use case. I'm creating a PDF using react and the only way I can display an image is through `<img src="">` so I need to be able to convert the dicom to a base64 string.

Does anyone know how can I achieve that ?

**Comment by kevinleedrum** [comment]
You can get base-64 from the canvas. https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

`const base64 = canvas.toDataURL()`

**Comment by GregdTd** [comment]
@kevinleedrum hello, thank you for your quick answer ! 

Maybe I was not clear enough sorry for that. 
There is no canvas in my use case.. The code I posted above was just an example ! 
What I want to achieve is something like:

```
const imageId = cornerstoneWADOImageLoader.wadouri.fileManager.add(currentFiles[0].data);
cornerstone.loadImage(imageId).then((image: any) => {
    // create a base64 string for each image
});
```

Because later I need a base64 string to display an image in a PDF using: https://react-pdf.org/components#image

Hope it's better ? Don't hesitate if you have question

**Comment by GregdTd** [comment]
Hello again,
Anyone is able to help ? @kevinleedrum @chafey

Thank you for your time !

**Comment by chafey** [comment]
CornerstoneJS requires a canvas to render.  Can you create a hidden canvas
and render into it?

**Comment by GregdTd** [comment]
I tried and it does work indeed.. But to be honest I have more than 20 dicoms to load, so create more than 20 hidden canvas in the dom just to be able to get the base64 string was a bit over-engineered IMO.. 
Thank you for your reply. I thought it would be an easy task but it seems a bit more complicated than expected..

**Comment by chafey** [comment]
You can re-use the same canvas, you don't need a canvas per image.  Your
use case is not the primary goal of the project - but you having to write a
few extra lines of code is much less than building all the code to parse
and view dicom :)

**Comment by GregdTd** [comment]
Yes sure you're right ! Last question, is there a way to wait for cornerstone to display the image ?
The displayImage seems to be asynchrone no ?

When executing code below the Canvas1 is not the corresponding base64 image but the Canvas2 is!!! 
```
for (let i = 0; i < files.length; i++) {
    const file = files[i];
    
    const imageId = cornerstoneWADOImageLoader.wadouri.fileManager.add(file);
    const element = document.getElementById('dicomCanvas');
    cornerstone.enable(element);
    
    cornerstone.loadImage(imageId).then((image: any) => {

          cornerstone.displayImage(element, image);

          if (element) {

              const domCanvas = element.querySelector('canvas');

              if (domCanvas && domCanvas !== null) {
                  const canvas: HTMLCanvasElement = domCanvas;
                  console.log('Canvas1:', canvas.toDataURL());
                  
                  setTimeout(() => {console.log('Canvas2:', canvas.toDataURL());}, 1000);

              }
         }
    });
}
```

**Comment by GregdTd** [comment]
Hello @chafey,
Sorry to bother again, did you have a look?
Have a good day !
