### ISSUE TITLE
convertPALETTECOLOR not handling special cases

### ISSUE THREAD

**Issue by nyej** [cornerstonejs/cornerstoneWADOImageLoader#42]
Special cases not handled by the current implementation
- The implementation does not consider BE data
- The implementation does not handle the scenario in which the LUT descriptor has a bits allocated value of 8 but the actual LUT sample size is 16 bits. (See second note in PS3.3 C.7.6.3.1.5)

Suggested change:
- The implementation should first convert the LUTs to 8 bit prior to the loop so that the loop can use clean LUT values and avoid shifting repeatedly for every pixel. Not a big deal but pre-processing is preferred.

**Comment by dannyrb** [comment]
I _think_ this was addressed in PR #138. If you're still experiencing issues, please let me know and I will re-open. Any test cases or reproductions you can provide would be helpful.
