### ISSUE TITLE
Hi guys, I've noticed the same issue. I've been using cornestone for years but with small images it's hard to detect thememory leak.

### ISSUE THREAD

**Issue by wangtiechuan** [cornerstonejs/cornerstoneWADOImageLoader#428]
Hi guys, I've noticed the same issue. I've been using cornestone for years but with small images it's hard to detect thememory leak.

I ran into it a few days ago while playing with the [official cornerstone multiframe example](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/examples/wadourimultiframe/index.html).

Instead using the data provided in the example (80kb, 2 frames), change url and use [this one](https://test-data.r1-it.storage.cloud.it/MultiFrame_Anon.dcm).
It's an anonymized cardiac angiogram (https://www.medicalconnections.co.uk/Sample-Images/)

As you can see, the memory increases (400mb) every time the frame changes.
It's not cornerstone tool, the playClip tool simply calls `loadImage` .
It's not cornestone imagecache (you can set the cache to 0 manually with `imageCache.setMaximumSizeBytes(0)`).

It seems that every time loadImage is called old typed arrays are still in memory and/or garbage collector is not able to clean the old arrays.

Any suggestion? Thanks!

_Originally posted by @daron1337 in https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/156#issuecomment-794628050_

**Comment by wangtiechuan** [comment]
![image](https://user-images.githubusercontent.com/23370689/153156716-01c7ef96-5b22-44a5-afca-15b61d88aaa9.png)

**Comment by wangtiechuan** [comment]
I use compressed DICOM data

**Comment by wangtiechuan** [comment]
The original data memory does not fluctuate greatly, but the compressed files will occupy special memory

**Comment by wangtiechuan** [comment]
@jmhmd @medihack @simonmd @malaterre  Thanks for your help. How can I solve this problem

**Comment by KeQianWang** [comment]
I have also encountered this problem recently. The memory of the browser has been rising due to the ultrasonic multi frame data (200K, 100 frames). What is the solution?

**Comment by wangtiechuan** [comment]
> I have also encountered this problem recently. The memory of the browser has been rising due to the ultrasonic multi frame data (200K, 100 frames). What is the solution?

更换为压缩率高一点的压缩算法，我原先用的91，现在是70，就暂时没出过问题了（不想翻译了，嘿嘿）

**Comment by dereklukacs** [comment]
> > I have also encountered this problem recently. The memory of the browser has been rising due to the ultrasonic multi frame data (200K, 100 frames). What is the solution?
> 
> 更换为压缩率高一点的压缩算法，我原先用的91，现在是70，就暂时没出过问题了（不想翻译了，嘿嘿）

Google translate: Replace it with a compression algorithm with a higher compression rate. I used 91 before, but now it is 70, and there has been no problem for the time being (I don't want to translate, hehe)
