### ISSUE TITLE
Memory Excepcion OHIF

### ISSUE THREAD

**Issue by ArturRod** [cornerstonejs/cornerstoneWADOImageLoader#446]
When opening ultrasound studies there is a memory failure, these studies must occupy approximately >100mb.
I haven't found any solution. Tried increasing node memory and nothing. I don't know what it is due to.
![image](https://user-images.githubusercontent.com/86238895/164713965-ba302446-129d-4fe6-b243-d10c48473e05.png)

**Comment by Ouwen** [comment]
@ArturRod do you have a file which you can upload?

**Comment by Ouwen** [comment]
Also #454 for a potential PR fix

**Comment by ArturRod** [comment]
Hi @Ouwen and @dereklukacs 
Thanks for the contribution, I will try this to see if it works, and I will try to implement it in OHIF.
Thank you very much :)
