### ISSUE TITLE
about load index.worker.min.worker.js

### ISSUE THREAD

**Issue by robustNan** [cornerstonejs/cornerstoneWADOImageLoader#461]
**When I use cornerstone-wado-image-loader in my vue project, index.worker.min.worker.js is loaded from http://localhost:8080/js/index.worker.min.worker.js, which should is the file in cornerstone-wado-image-loader/dist/dynamic-import. Now, I can only create the js directory in the root directory and copy index.worker.min.worker.js into it, otherwise the browser will report an error (Uncaught SyntaxError: Unexpected token '<' (at index.worker.min.worker.js:1:1))**

![image](https://user-images.githubusercontent.com/31467519/181187584-3cbcafb7-676d-4c6a-bbb3-eb37e323468b.png)

![image](https://user-images.githubusercontent.com/31467519/181187845-ce4e636b-fda8-489b-aae1-97e3f533d293.png)

**In addition, if my maxWebWorkers property setting is greater than 3, the browser will crash/(ㄒoㄒ)/~~**

My vue.config.js
```js
const CopyWebpackPlugin = require('copy-webpack-plugin')
const path = require('path')

const DIST_DIR = path.resolve(__dirname, 'dist')

module.exports = {
  chainWebpack: config => {
    config.module
      .rule('babel-loader')
      .test(/\.js|jsx$/)
      .use('babel-loader')
      .loader('babel-loader')
      .end()

    config.resolve.alias.set('cornerstone-wado-image-loader', 'cornerstone-wado-image-loader/dist/dynamic-import/cornerstoneWADOImageLoader.min.js')
  },
  devServer: {
    hot: true,
    proxy: {
      [process.env.VUE_APP_DICOM_WEB]: {
        // target: 'https://d1qmxk7r72ysft.cloudfront.net',
        target: 'http://192.168.94.27:8042',
        changeOrigin: true,
        pathRewrite: path => path.replace(/^\/dicom/, ''),
      },
    },
    headers: {
      'Cross-Origin-Embedder-Policy': 'require-corp',
      'Cross-Origin-Opener-Policy': 'same-origin',
    },
  },
  configureWebpack: {
    plugins: [
      new CopyWebpackPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, 'node_modules/cornerstone-wado-image-loader/dist/dynamic-import'),
            to: DIST_DIR,
          },
        ],
      }),
    ],
  },
}
```

My CornerstonePractice.vue
```js
import cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader/dist/dynamic-import/cornerstoneWADOImageLoader.min.js'
...
cornerstoneWADOImageLoader.external.cornerstone = cornerstone
cornerstoneWADOImageLoader.external.dicomParser = dicomParser
cornerstoneWADOImageLoader.configure({
  useWebWorkers: true,
  decodeConfig: {
    convertFloatPixelDataToInt: false,
  },
  // beforeSend
})

const config = {
  maxWebWorkers: Math.min(navigator.hardwareConcurrency, 3),
  // maxWebWorkers: navigator.hardwareConcurrency || 1,
  startWebWorkersOnDemand: false,
  taskConfiguration: {
    decodeTask: {
      initializeCodecsOnStartup: true,
      strict: false,
    },
  },
}

cornerstoneWADOImageLoader.webWorkerManager.initialize(config)
```

**Comment by zhoualibaba** [comment]
Have you solved this problem?
I have the same problem.

**Comment by robustNan** [comment]
> @robustNan Have you solved this problem? I have the same problem.

const DIST_DIR = path.resolve(__dirname, 'dist/js')

**Comment by robustNan** [comment]
> @robustNan Have you solved this problem? I have the same problem.

看你名字应该是中国人，我就写中文吧。把 DIST_DIR 定义到 'dist/js'，因为它是从根目录下的js目录中获取work文件，所以这里要把npm包里的work文件复制到打包目录下名称为js的目录中

**Comment by zhoualibaba** [comment]
> 

感谢您的回复，问题解决了。

**Comment by zhoualibaba** [comment]
> 

可以，联系方式可以发我邮箱
